<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6900f8acade0ed2d9046f99c1f89b468
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Roots\\Composer\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Roots\\Composer\\' => 
        array (
            0 => __DIR__ . '/..' . '/roots/wordpress-core-installer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6900f8acade0ed2d9046f99c1f89b468::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6900f8acade0ed2d9046f99c1f89b468::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6900f8acade0ed2d9046f99c1f89b468::$classMap;

        }, null, ClassLoader::class);
    }
}
